# Column Transformer

In [59]:
import numpy as np
import pandas as pd

In [60]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [61]:
df = pd.read_csv('covid_toy.csv')

In [62]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

* Age --> Simple Imputer
* city & gender --> One Hot Encoding
* fever & cough --> Ordinal Encoder




The **SimpleImputer:** is used to fill in missing values in your dataset. It's best suited for numerical columns, like your 'age' column, where missing data could be a problem for machine learning algorithms.

In [63]:
df["city"].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [64]:
df["cough"].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [65]:
df["fever"].describe()

count     90.000000
mean     100.844444
std        2.054926
min       98.000000
25%       99.000000
50%      101.000000
75%      102.750000
max      104.000000
Name: fever, dtype: float64

## Do we have any missing data in our columns ?

In [66]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

## fever p simple imputer lagega

In [67]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']), df['has_covid'], test_size= 0.2)

In [68]:
X_train

age  gender  fever   cough       city
39   50  Female  103.0    Mild    Kolkata
91   38    Male    NaN    Mild      Delhi
69   73  Female  103.0    Mild      Delhi
72   83  Female  101.0    Mild    Kolkata
17   40  Female   98.0  Strong      Delhi
..  ...     ...    ...     ...        ...
32   34  Female  101.0  Strong      Delhi
37   55    Male  100.0    Mild    Kolkata
7    20  Female    NaN  Strong     Mumbai
97   20  Female  101.0    Mild  Bangalore
85   16  Female  103.0    Mild  Bangalore

[80 rows x 5 columns]

# **1. Aam Zindagi** 😒

#### lets handle missing values in fever column using simple imputer first

In [69]:
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[["fever"]])
X_test_fever = si.fit_transform(X_test[["fever"]])
X_train_fever.shape

(80, 1)

In [81]:
X_test_fever.shape

(20, 1)

In [70]:
X_train_fever

array([[103.        ],
       [100.98611111],
       [103.        ],
       [101.        ],
       [ 98.        ],
       [104.        ],
       [101.        ],
       [ 98.        ],
       [ 98.        ],
       [103.        ],
       [ 98.        ],
       [103.        ],
       [ 98.        ],
       [101.        ],
       [100.        ],
       [100.98611111],
       [100.98611111],
       [100.        ],
       [ 99.        ],
       [101.        ],
       [102.        ],
       [103.        ],
       [102.        ],
       [104.        ],
       [104.        ],
       [101.        ],
       [103.        ],
       [100.        ],
       [103.        ],
       [ 98.        ],
       [102.        ],
       [ 98.        ],
       [101.        ],
       [101.        ],
       [100.98611111],
       [104.        ],
       [104.        ],
       [ 98.        ],
       [100.98611111],
       [102.        ],
       [101.        ],
       [102.        ],
       [102.        ],
       [102

# Now lets perform Ordinal Encoding

In [71]:
oe = OrdinalEncoder(categories=[["Mild","Strong" ]])
X_train_cough = oe.fit_transform(X_train[["cough"]])
X_test_cough = oe.fit_transform(X_test[["cough"]])
X_train_cough.shape

(80, 1)

In [82]:
X_test_cough.shape

(20, 1)

In [72]:
X_train_cough

array([[0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],

## One Hot Encoding -> Gender, city

In [73]:
ohe = OneHotEncoder()
X_train_gender_city = ohe.fit_transform(X_train[["gender", "city"]])
X_test_gender_city = ohe.fit_transform(X_test[["gender","city"]])
X_train_gender_city.shape

(80, 6)

## Multicolinearity remove

In [83]:
X_test_gender_city.shape

(20, 4)

In [74]:
ohe = OneHotEncoder(drop="first", sparse=False)
X_train_gender_city = ohe.fit_transform(X_train[["gender", "city"]])
X_test_gender_city = ohe.fit_transform(X_test[["gender","city"]])
X_train_gender_city.shape

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


(80, 4)

In [75]:
X_train_gender_city

array([[0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],


## Now we will concatenate everything to form a good refined database


lets extract age colum first from the database

In [85]:
X_train_age = X_train.drop(columns=["gender", "fever", "cough", "city"]).values
X_test_age = X_test.drop(columns=["gender", "fever", "cough", "city"]).values
X_train_age.shape

(80, 1)

In [77]:
type(X_train.drop(columns=["gender", "fever", "cough", "city"]))

pandas.core.frame.DataFrame

In [78]:
#X_train.drop(columns=["gender", "fever", "cough", "city"])

In [86]:
X_test_age.shape

(20, 1)

In [79]:
#X_train.drop(columns=["gender", "fever", "cough", "city"]).values

# Now lets make it concatenate

In [87]:
X_train_transformed = np.concatenate((X_train_age, X_train_fever, X_train_gender_city, X_train_cough), axis=1)
X_test_transformed = np.concatenate((X_test_age, X_test_fever, X_test_gender_city, X_test_cough), axis=1)
X_train_transformed.shape

(80, 7)

In [88]:
X_train_transformed

array([[ 50.        , 103.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 38.        , 100.98611111,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 73.        , 103.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 83.        , 101.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 40.        ,  98.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 17.        , 104.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 19.        , 101.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 24.        ,  98.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 12.        ,  98.        ,   1.        ,   0.        ,
          0.    

## **2. Mentos Zindgi** 😇

In [89]:
from sklearn.compose import ColumnTransformer

In [91]:
transformers = [
    ("transormer1", SimpleImputer(), ["fever"]),
    ("transformer2", OrdinalEncoder(categories=[["Mild", "Strong"]]), ["cough"]),
    ("transformer3", OneHotEncoder(sparse=False,drop="first"), ["gender", "city"])
]

In [92]:
transformer = ColumnTransformer(transformers,remainder="passthrough")

In [96]:
Mentos_transform = transformer.fit_transform(X_train).shape

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [94]:
transformer.fit_transform(X_test).shape

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


(20, 7)

In [100]:
type(Mentos_transform)

tuple

In [101]:
Mentos_transform

(80, 7)
