In [59]:
import pickle
import numpy as np

In [60]:
ohe_sex = pickle.load(open('ohe_sex.pkl', 'rb'))
ohe_embarked = pickle.load(open('ohe_embarked.pkl', 'rb'))
clf = pickle.load(open('model.pkl', 'rb'))

In [61]:
# passing some user input
test_input = np.array([2,'male', 31.0,0,0,10.5, 'S'], dtype=object).reshape(1,7)

In [62]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [63]:
test_input[:,1].reshape(1,1)

array([['male']], dtype=object)

In [64]:
ohe_sex

OneHotEncoder(handle_unknown='ignore', sparse=False, sparse_output=False)

In [65]:
test_input[:,1].reshape(1,1)

array([['male']], dtype=object)

In [66]:
type(ohe_sex)

sklearn.preprocessing._encoders.OneHotEncoder

In [67]:
# Now you should be able to use transform
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [68]:
test_input_sex

array([[0., 1.]])

In [69]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [70]:
test_input_embarked

array([[0., 0., 1.]])

In [71]:
test_input = np.concatenate((test_input[:,[0,2,3,4,5]], test_input_sex, test_input_embarked),axis = 1)

In [72]:
test_input

array([[2, 31.0, 0, 0, 10.5, 0.0, 1.0, 0.0, 0.0, 1.0]], dtype=object)

In [73]:
test_input.shape

(1, 10)

In [74]:
clf.predict(test_input)

array([0])